name: .NET + Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore HairWizard.sln

      - name: Build
        run: dotnet build HairWizard.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test HairWizard.sln --no-build --configuration Release --verbosity normal

  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Debug repo state
        run: |
                echo "=== ROOT ==="
                ls -la
                echo
                echo "=== .github/workflows ==="
                ls -la .github/workflows || true
                echo
                echo "=== HairWizard ==="
                ls -la ./HairWizard
                echo
                echo "=== Find csproj ==="
                find . -name "*.csproj"
                echo
                echo "=== Dockerfile content ==="
                cat ./HairWizard/Dockerfile
                echo
                echo "=== .dockerignore content ==="
                cat .dockerignore || true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./HairWizard
          file: ./HairWizard/Dockerfile
          push: true
          tags: jkaa81/hairwizard-repo:latest
      deploy:
    runs-on: ubuntu-latest
    needs: docker
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: ${{ secrets.DO_PORT }}
          script: |
            docker pull jkaa81/hairwizard-repo:latest
            docker stop hairwizard || true
            docker rm hairwizard || true
            docker run -d \
              --name hairwizard \
              --restart unless-stopped \
              -e ASPNETCORE_URLS=http://+:8080 \
              -p 8080:8080 \
              jkaa81/hairwizard-repo:latest
